In [35]:
import numpy as np
import time

# Vectors

## Vector Creation

In [36]:
# NumPy routines which allocate memory and fill arrays with value
a = np.zeros(4)
# here argument is integer
print(f"np.zeros(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.zeros((4,))
# here argument is tuple with only one value(4)
print(f"np.zeros(4,): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.random_sample(4)
# default value 0.0≤x<1.0
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,): a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.44236513 0.04997798 0.77390955 0.93782363], a shape = (4,), a data type = float64


In [37]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument
a = np.arange(4.)
print(f"np.arange(4.): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
a = np.random.rand(3)
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")
# random_sample() and rand() do the same thing
# difference is their argument differ as random_sample() can take a tuple

np.arange(4.): a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.5792328  0.53516563 0.80204309], a shape = (3,), a data type = float64


In [38]:
# NumPy routines which allocate memory and fill with user specified values
a = np.array([5,4,3,2]);  print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")
a = np.array([5.,4,3,2]); print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


## Operations on Vectors

### Indexing

In [39]:
a = np.arange(10)
print(a)

# access an element
print(f"a[2].shape = {a[2].shape} a[2] = {a[2]}, Accessing an element returns a scalar")

# negative indexes count from the end
print(f"a[-1] = {a[-1]}")

# indexes must be within the range of the vector or they will produce an error.
try:
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape = () a[2] = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


### Slicing
- Slicing use set of three values [Start:Stop:Stop]

In [40]:
a = np.arange(10)
print(f"a = {a}")

c = a[2:7:1]
print(c)
c = a[2:7:2]
print(c)
c = a[3:]
print(c)
c = a[:3]
print(c)
c = a[:]
print(c)

a = [0 1 2 3 4 5 6 7 8 9]
[2 3 4 5 6]
[2 4 6]
[3 4 5 6 7 8 9]
[0 1 2]
[0 1 2 3 4 5 6 7 8 9]


### Single Vector Operations

In [41]:
a = np.array([1,2,3,4])
print(f"a = {a}")
# negate elements of a
b = -a
print(f"b = -a: {b}")

b = np.sum(a)
print(f"b = np.sum(a): {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2: {b}")

a = [1 2 3 4]
b = -a: [-1 -2 -3 -4]
b = np.sum(a): 10
b = np.mean(a): 2.5
b = a**2: [ 1  4  9 16]


### Vector Vector element-wise operations
- Most of the NumPy arithmetic, logical and comparison operatins apply to vectors as well.  
$c_i$= $a_i + b_i$


In [42]:
a = np.array([1,2,3,4])
b = np.array([-1,-2,3,4])
print(f"Binary operator work element wise: {a + b}")
# Vector size must be same

Binary operator work element wise: [0 0 6 8]


In [43]:
# try a mismatched vector size
c = np.array([1,2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


### Scalar Vector operations

In [44]:
a = np.array([1,2,3,4])

b = 5*a
print(f"b = 5*a: {b}")

b = 5*a: [ 5 10 15 20]


### Vector Vector dot product
- dot product returns a scalar value

In [45]:
# using for loop
# assume a and b are of same size
def my_dot(a, b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i] * b[i]

    return x

In [46]:
# test 1-D
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])
print(f"my_dot(a,b) = {my_dot(a,b)}")

my_dot(a,b) = 24


In [47]:
# now using np.dot on 1-D
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])
c = np.dot(a,b)
print(f"NumPy 1-D np.dot(a,b) = {c}, np.dot(a,b).shape = {c.shape}")
c = np.dot(b,a)
print(f"NumPy 1-D np.dot(b,a) = {c}, np.dot(b,a).shape = {c.shape}")

NumPy 1-D np.dot(a,b) = 24, np.dot(a,b).shape = ()
NumPy 1-D np.dot(b,a) = 24, np.dot(b,a).shape = ()


### The Need for Speed: vector vs for loop

In [48]:
np.random.seed(1)
# seed() is like random_state but here it is for producing arrays
a = np.random.rand(10000000)
b = np.random.rand(10000000)
tic = time.time() # tic capture start time
c = np.dot(a,b)
toc = time.time()# toc capture end time
# time.time() returns the total seconds passed since Jan 1, 1970 00:00:00 UTC
# up to the moment time.time() is executed
print(f"np.dot(a,b) = {c:.4f}")
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms")

tic = time.time()
c = my_dot(a,b)
toc = time.time()

print(f"my_dot(a,b) = {c:.4f}")
print(f"Loop version duration: {1000*(toc-tic):.4f} ms")

del(a)
del(b)
# remove these big arrays from memory

np.dot(a,b) = 2501072.5817
Vectorized version duration: 4.1642 ms
my_dot(a,b) = 2501072.5817
Loop version duration: 1471.3652 ms


In [49]:
X = np.array([[1],[2],[3],[4]])
w = np.array([2])
c = np.dot(X[1], w)

print(f"X[1] has shape {X[1].shape}")
print(f"w has shape {w.shape}")
print(f"c has shape {c.shape}")

X[1] has shape (1,)
w has shape (1,)
c has shape ()
